
//----------------------------------------------------
// The following code was generated by CUP v0.10k TUM Edition 20050516
// Wed May 20 02:12:27 PDT 2015
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int T_WHILE = 62;
  public static final int T_INT_LITERAL = 65;
  public static final int T_FLOAT = 25;
  public static final int T_LTE = 37;
  public static final int T_ELSE = 19;
  public static final int T_STATIC = 57;
  public static final int T_RPAREN = 52;
  public static final int T_CONTINUE = 15;
  public static final int T_DELETE = 17;
  public static final int T_COUT = 16;
  public static final int T_SIZEOF = 54;
  public static final int T_NULLPTR = 44;
  public static final int T_FALSE = 24;
  public static final int T_INT = 31;
  public static final int T_MINUSMINUS = 39;
  public static final int T_EXTERN = 23;
  public static final int T_ASSIGN = 5;
  public static final int T_BAR = 6;
  public static final int T_RETURN = 51;
  public static final int T_NOT = 43;
  public static final int T_AND = 3;
  public static final int T_CONST = 14;
  public static final int T_SLASH = 55;
  public static final int T_COLONCOLON = 12;
  public static final int T_GT = 28;
  public static final int T_STRUCTDEF = 58;
  public static final int T_RBRACKET = 50;
  public static final int T_DOT = 18;
  public static final int EOF = 0;
  public static final int T_MINUS = 38;
  public static final int T_TILDE = 60;
  public static final int T_LBRACE = 33;
  public static final int error = 1;
  public static final int T_SEMI = 53;
  public static final int T_NEW = 41;
  public static final int T_ID_U = 67;
  public static final int T_FLOAT_LITERAL = 64;
  public static final int T_MOD = 40;
  public static final int T_RBRACE = 49;
  public static final int T_NEQ = 42;
  public static final int T_CIN = 10;
  public static final int T_COMMA = 13;
  public static final int T_STAR = 56;
  public static final int T_GTE = 29;
  public static final int T_ENDL = 20;
  public static final int T_EQU = 21;
  public static final int T_CARET = 9;
  public static final int T_BOOL = 7;
  public static final int T_PLUS = 47;
  public static final int T_EXIT = 22;
  public static final int T_LT = 36;
  public static final int T_STR_LITERAL = 66;
  public static final int T_THIS = 59;
  public static final int T_OR = 45;
  public static final int T_AMPERSAND = 2;
  public static final int T_BREAK = 8;
  public static final int T_TRUE = 61;
  public static final int T_ISTREAM = 32;
  public static final int T_FOREACH = 26;
  public static final int T_OSTREAM = 46;
  public static final int T_IF = 30;
  public static final int T_PLUSPLUS = 48;
  public static final int T_ARROW = 4;
  public static final int T_ID = 68;
  public static final int T_COLON = 11;
  public static final int T_FUNCTION = 27;
  public static final int T_VOID = 63;
  public static final int T_LBRACKET = 34;
  public static final int T_LPAREN = 35;
}

